# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_math_solver_query.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$lens_overlay_math_solver_query.proto\x12\x04lens".\n\x0fMathSolverQuery\x12\x1b\n\x13math_input_equation\x18\x03 \x01(\tB\x02H\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_math_solver_query_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _MATHSOLVERQUERY._serialized_start = 46
    _MATHSOLVERQUERY._serialized_end = 92
# @@protoc_insertion_point(module_scope)
