# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_request_id.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_routing_info_pb2 as lens__overlay__routing__info__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dlens_overlay_request_id.proto\x12\x04lens\x1a\x1flens_overlay_routing_info.proto"\xcf\x04\n\x14LensOverlayRequestId\x12\x0c\n\x04uuid\x18\x01 \x01(\x04\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x05\x12\x19\n\x11image_sequence_id\x18\x03 \x01(\x05\x12\x14\n\x0c\x61nalytics_id\x18\x04 \x01(\x0c\x12\x17\n\x0flong_context_id\x18\t \x01(\x05\x12\x32\n\x0crouting_info\x18\x06 \x01(\x0b\x32\x1c.lens.LensOverlayRoutingInfo\x12\x11\n\ttime_usec\x18\x07 \x01(\x04\x12\x38\n\nmedia_type\x18\n \x01(\x0e\x32$.lens.LensOverlayRequestId.MediaType\x12\x12\n\ncontext_id\x18\x0c \x01(\x03\x12\x11\n\tmime_type\x18\r \x01(\t\x12\x1b\n\x13has_chrome_tab_data\x18\x0f \x01(\x08\x12\x1a\n\x12is_implicit_upload\x18\x10 \x01(\x08"\xe8\x01\n\tMediaType\x12\x1c\n\x18MEDIA_TYPE_DEFAULT_IMAGE\x10\x00\x12\x12\n\x0eMEDIA_TYPE_PDF\x10\x01\x12\x16\n\x12MEDIA_TYPE_WEBPAGE\x10\x02\x12\x1c\n\x18MEDIA_TYPE_PDF_AND_IMAGE\x10\x03\x12 \n\x1cMEDIA_TYPE_WEBPAGE_AND_IMAGE\x10\x04\x12\x1d\n\x19MEDIA_TYPE_UNRESOLVED_URL\x10\x05\x12\x17\n\x13MEDIA_TYPE_RAW_FILE\x10\x06\x12\x19\n\x15MEDIA_TYPE_UNRESOLVED\x10\x07\x42\x02H\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_request_id_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _LENSOVERLAYREQUESTID._serialized_start = 73
    _LENSOVERLAYREQUESTID._serialized_end = 664
    _LENSOVERLAYREQUESTID_MEDIATYPE._serialized_start = 432
    _LENSOVERLAYREQUESTID_MEDIATYPE._serialized_end = 664
# @@protoc_insertion_point(module_scope)
