# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_visual_search_interaction_log_data.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'lens_overlay_visual_search_interaction_log_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_client_platform_pb2 as lens__overlay__client__platform__pb2
import lens_overlay_filters_pb2 as lens__overlay__filters__pb2
import lens_overlay_selection_type_pb2 as lens__overlay__selection__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5lens_overlay_visual_search_interaction_log_data.proto\x12\x04lens\x1a\"lens_overlay_client_platform.proto\x1a\x1alens_overlay_filters.proto\x1a!lens_overlay_selection_type.proto\"\x8e\x02\n)LensOverlayVisualSearchInteractionLogData\x12\x31\n\x0b\x66ilter_data\x18\x01 \x01(\x0b\x32\x10.lens.FilterDataR\nfilterData\x12G\n\x13user_selection_data\x18\x02 \x01(\x0b\x32\x17.lens.UserSelectionDataR\x11userSelectionData\x12&\n\x0fis_parent_query\x18\x03 \x01(\x08R\risParentQuery\x12=\n\x0f\x63lient_platform\x18\x04 \x01(\x0e\x32\x14.lens.ClientPlatformR\x0e\x63lientPlatform\"J\n\nFilterData\x12<\n\x0b\x66ilter_type\x18\x01 \x01(\x0e\x32\x1b.lens.LensOverlayFilterTypeR\nfilterType\"Z\n\x11UserSelectionData\x12\x45\n\x0eselection_type\x18\x01 \x01(\x0e\x32\x1e.lens.LensOverlaySelectionTypeR\rselectionTypeB\x02H\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_visual_search_interaction_log_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LENSOVERLAYVISUALSEARCHINTERACTIONLOGDATA']._serialized_start=163
  _globals['_LENSOVERLAYVISUALSEARCHINTERACTIONLOGDATA']._serialized_end=433
  _globals['_FILTERDATA']._serialized_start=435
  _globals['_FILTERDATA']._serialized_end=509
  _globals['_USERSELECTIONDATA']._serialized_start=511
  _globals['_USERSELECTIONDATA']._serialized_end=601
# @@protoc_insertion_point(module_scope)
