# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_image_crop.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 4, "", "lens_overlay_image_crop.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
import lens_overlay_payload_pb2 as lens__overlay__payload__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x1dlens_overlay_image_crop.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a\x1alens_overlay_payload.proto\"\x8d\x01\n\tImageCrop\x12\x1e\n\x07\x63rop_id\x18\x01 \x01(\tB\x05\xaa\x01\x02\x08\x02R\x06\x63ropId\x12'\n\x05image\x18\x02 \x01(\x0b\x32\x11.lens.ClientImageR\x05image\x12\x31\n\x0bzoomed_crop\x18\x03 \x01(\x0b\x32\x10.lens.ZoomedCropR\nzoomedCropJ\x04\x08\x04\x10\x05\x42\x02H\x03\x62\x08\x65\x64itionsp\xe8\x07"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_image_crop_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_IMAGECROP"].fields_by_name["crop_id"]._loaded_options = None
    _globals["_IMAGECROP"].fields_by_name[
        "crop_id"
    ]._serialized_options = b"\252\001\002\010\002"
    _globals["_IMAGECROP"]._serialized_start = 97
    _globals["_IMAGECROP"]._serialized_end = 238
# @@protoc_insertion_point(module_scope)
