# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_geometry.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'lens_overlay_geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_polygon_pb2 as lens__overlay__polygon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blens_overlay_geometry.proto\x12\x04lens\x1a\x1alens_overlay_polygon.proto\"\xd4\x01\n\x10\x43\x65nterRotatedBox\x12\x19\n\x08\x63\x65nter_x\x18\x01 \x01(\x02R\x07\x63\x65nterX\x12\x19\n\x08\x63\x65nter_y\x18\x02 \x01(\x02R\x07\x63\x65nterY\x12\x14\n\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x02R\x06height\x12\x1d\n\nrotation_z\x18\x05 \x01(\x02R\trotationZ\x12=\n\x0f\x63oordinate_type\x18\x06 \x01(\x0e\x32\x14.lens.CoordinateTypeR\x0e\x63oordinateType\"\x9f\x01\n\x08Geometry\x12\x39\n\x0c\x62ounding_box\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBoxR\x0b\x62oundingBox\x12@\n\x14segmentation_polygon\x18\x05 \x03(\x0b\x32\r.lens.PolygonR\x13segmentationPolygonJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x06\x10\x07\"\x94\x01\n\nZoomedCrop\x12*\n\x04\x63rop\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBoxR\x04\x63rop\x12!\n\x0cparent_width\x18\x02 \x01(\x05R\x0bparentWidth\x12#\n\rparent_height\x18\x03 \x01(\x05R\x0cparentHeight\x12\x12\n\x04zoom\x18\x04 \x01(\x02R\x04zoomB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CENTERROTATEDBOX']._serialized_start=66
  _globals['_CENTERROTATEDBOX']._serialized_end=278
  _globals['_GEOMETRY']._serialized_start=281
  _globals['_GEOMETRY']._serialized_end=440
  _globals['_ZOOMEDCROP']._serialized_start=443
  _globals['_ZOOMEDCROP']._serialized_end=591
# @@protoc_insertion_point(module_scope)
