# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_visual_search_interaction_data.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    "",
    "lens_overlay_visual_search_interaction_data.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
import lens_overlay_interaction_request_metadata_pb2 as lens__overlay__interaction__request__metadata__pb2
import lens_overlay_visual_search_interaction_log_data_pb2 as lens__overlay__visual__search__interaction__log__data__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n1lens_overlay_visual_search_interaction_data.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a/lens_overlay_interaction_request_metadata.proto\x1a\x35lens_overlay_visual_search_interaction_log_data.proto"\xd4\x03\n&LensOverlayVisualSearchInteractionData\x12[\n\x10interaction_type\x18\x01 \x01(\x0e\x32\x30.lens.LensOverlayInteractionRequestMetadata.TypeR\x0finteractionType\x12\x31\n\x0bzoomed_crop\x18\x07 \x01(\x0b\x32\x10.lens.ZoomedCropR\nzoomedCrop\x12\x1b\n\tobject_id\x18\x03 \x01(\tR\x08objectId\x12X\n\x0btext_select\x18\x04 \x01(\x0b\x32\x37.lens.LensOverlayVisualSearchInteractionData.TextSelectR\ntextSelect\x12J\n\x08log_data\x18\x05 \x01(\x0b\x32/.lens.LensOverlayVisualSearchInteractionLogDataR\x07logData\x1aK\n\nTextSelect\x12%\n\x0eselected_texts\x18\x05 \x01(\tR\rselectedTextsJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x02\x10\x03J\x04\x08\x06\x10\x07\x42\x07H\x03\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_visual_search_interaction_data_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003\222\003\002\010\002"
    _globals["_LENSOVERLAYVISUALSEARCHINTERACTIONDATA"]._serialized_start = 193
    _globals["_LENSOVERLAYVISUALSEARCHINTERACTIONDATA"]._serialized_end = 661
    _globals["_LENSOVERLAYVISUALSEARCHINTERACTIONDATA_TEXTSELECT"]._serialized_start = (
        574
    )
    _globals["_LENSOVERLAYVISUALSEARCHINTERACTIONDATA_TEXTSELECT"]._serialized_end = 649
# @@protoc_insertion_point(module_scope)
