# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_knowledge_intent_query.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'lens_overlay_knowledge_intent_query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_translate_stickiness_signals_pb2 as lens__overlay__translate__stickiness__signals__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lens_overlay_knowledge_intent_query.proto\x12\x04lens\x1a/lens_overlay_translate_stickiness_signals.proto\"\x83\x01\n\x0c\x46unctionCall\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12*\n\x08\x61rgument\x18\x02 \x03(\x0b\x32\x0e.lens.ArgumentR\x08\x61rgument\x12\x33\n\x07signals\x18\x04 \x01(\x0b\x32\x19.lens.FunctionCallSignalsR\x07signals\"}\n\x13\x46unctionCallSignals\x12\x66\n\x1ctranslate_stickiness_signals\x18\xe6\x81\xbd\x94\x01 \x01(\x0b\x32 .lens.TranslateStickinessSignalsR\x1atranslateStickinessSignals\"I\n\x08\x41rgument\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x13.lens.ArgumentValueR\x05value\"P\n\rArgumentValue\x12\x36\n\x0csimple_value\x18\x03 \x01(\x0b\x32\x11.lens.SimpleValueH\x00R\x0bsimpleValueB\x07\n\x05value\";\n\x0bSimpleValue\x12#\n\x0cstring_value\x18\x01 \x01(\tH\x00R\x0bstringValueB\x07\n\x05valueB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_knowledge_intent_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_FUNCTIONCALL']._serialized_start=101
  _globals['_FUNCTIONCALL']._serialized_end=232
  _globals['_FUNCTIONCALLSIGNALS']._serialized_start=234
  _globals['_FUNCTIONCALLSIGNALS']._serialized_end=359
  _globals['_ARGUMENT']._serialized_start=361
  _globals['_ARGUMENT']._serialized_end=434
  _globals['_ARGUMENTVALUE']._serialized_start=436
  _globals['_ARGUMENTVALUE']._serialized_end=516
  _globals['_SIMPLEVALUE']._serialized_start=518
  _globals['_SIMPLEVALUE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
