# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_client_platform.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'lens_overlay_client_platform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"lens_overlay_client_platform.proto\x12\x04lens*Y\n\x0e\x43lientPlatform\x12\x1f\n\x1b\x43LIENT_PLATFORM_UNSPECIFIED\x10\x00\x12 \n\x1c\x43LIENT_PLATFORM_LENS_OVERLAY\x10\x02\x1a\x04:\x02\x10\x02\x42\x02H\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lens_overlay_client_platform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CLIENTPLATFORM']._loaded_options = None
  _globals['_CLIENTPLATFORM']._serialized_options = b':\002\020\002'
  _globals['_CLIENTPLATFORM']._serialized_start=44
  _globals['_CLIENTPLATFORM']._serialized_end=133
# @@protoc_insertion_point(module_scope)
