# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lens_overlay_filters.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1alens_overlay_filters.proto\x12\x04lens"\xcc\x01\n\rAppliedFilter\x12\x30\n\x0b\x66ilter_type\x18\x01 \x01(\x0e\x32\x1b.lens.LensOverlayFilterType\x12\x32\n\ttranslate\x18\x03 \x01(\x0b\x32\x1d.lens.AppliedFilter.TranslateH\x00\x1a\x43\n\tTranslate\x12\x17\n\x0ftarget_language\x18\x01 \x01(\t\x12\x1d\n\x0fsource_language\x18\x02 \x01(\t:\x04\x61utoB\x10\n\x0e\x66ilter_payload"5\n\x0e\x41ppliedFilters\x12#\n\x06\x66ilter\x18\x01 \x03(\x0b\x32\x13.lens.AppliedFilter*P\n\x15LensOverlayFilterType\x12\x17\n\x13UNKNOWN_FILTER_TYPE\x10\x00\x12\r\n\tTRANSLATE\x10\x02\x12\x0f\n\x0b\x41UTO_FILTER\x10\x07\x42\x02H\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_filters_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _LENSOVERLAYFILTERTYPE._serialized_start = 298
    _LENSOVERLAYFILTERTYPE._serialized_end = 378
    _APPLIEDFILTER._serialized_start = 37
    _APPLIEDFILTER._serialized_end = 241
    _APPLIEDFILTER_TRANSLATE._serialized_start = 156
    _APPLIEDFILTER_TRANSLATE._serialized_end = 223
    _APPLIEDFILTERS._serialized_start = 243
    _APPLIEDFILTERS._serialized_end = 296
# @@protoc_insertion_point(module_scope)
