# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_lens_file.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 4, "", "lens_overlay_lens_file.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1clens_overlay_lens_file.proto\x12\x04lens"\xd7\x01\n\x13LensOverlayLensFile\x12\x14\n\x05vsrid\x18\x01 \x01(\tR\x05vsrid\x12\x30\n\x14sticky_cluster_token\x18\x02 \x01(\tR\x12stickyClusterToken\x12\x1b\n\tmime_type\x18\x03 \x01(\tR\x08mimeType\x12\x1b\n\tfile_name\x18\x05 \x01(\tR\x08\x66ileName\x12\x1d\n\npage_title\x18\x06 \x01(\tR\tpageTitle\x12\x19\n\x08page_url\x18\x07 \x01(\tR\x07pageUrlJ\x04\x08\x04\x10\x05\x42\x02H\x03\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_lens_file_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_LENSOVERLAYLENSFILE"]._serialized_start = 39
    _globals["_LENSOVERLAYLENSFILE"]._serialized_end = 254
# @@protoc_insertion_point(module_scope)
