# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lens_overlay_interaction_request_metadata.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    "",
    "lens_overlay_interaction_request_metadata.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lens_overlay_geometry_pb2 as lens__overlay__geometry__pb2
import lens_overlay_text_query_pb2 as lens__overlay__text__query__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n/lens_overlay_interaction_request_metadata.proto\x12\x04lens\x1a\x1blens_overlay_geometry.proto\x1a\x1dlens_overlay_text_query.proto"\xa5\x08\n%LensOverlayInteractionRequestMetadata\x12\x44\n\x04type\x18\x01 \x01(\x0e\x32\x30.lens.LensOverlayInteractionRequestMetadata.TypeR\x04type\x12l\n\x12selection_metadata\x18\x02 \x01(\x0b\x32=.lens.LensOverlayInteractionRequestMetadata.SelectionMetadataR\x11selectionMetadata\x12`\n\x0equery_metadata\x18\x04 \x01(\x0b\x32\x39.lens.LensOverlayInteractionRequestMetadata.QueryMetadataR\rqueryMetadata\x1a\xef\x03\n\x11SelectionMetadata\x12[\n\x05point\x18\x01 \x01(\x0b\x32\x43.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.PointH\x00R\x05point\x12^\n\x06region\x18\x02 \x01(\x0b\x32\x44.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.RegionH\x00R\x06region\x12^\n\x06object\x18\x03 \x01(\x0b\x32\x44.lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.ObjectH\x00R\x06object\x1a#\n\x05Point\x12\x0c\n\x01x\x18\x01 \x01(\x02R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x02R\x01y\x1a\x38\n\x06Region\x12.\n\x06region\x18\x01 \x01(\x0b\x32\x16.lens.CenterRotatedBoxR\x06region\x1aQ\n\x06Object\x12\x1b\n\tobject_id\x18\x01 \x01(\tR\x08objectId\x12*\n\x08geometry\x18\x02 \x01(\x0b\x32\x0e.lens.GeometryR\x08geometryB\x0b\n\tselection\x1a\x45\n\rQueryMetadata\x12.\n\ntext_query\x18\x02 \x01(\x0b\x32\x0f.lens.TextQueryR\ttextQueryJ\x04\x08\x01\x10\x02"\xa6\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03TAP\x10\x01\x12\n\n\x06REGION\x10\x02\x12\x12\n\x0eTEXT_SELECTION\x10\x03\x12\x11\n\rREGION_SEARCH\x10\x04\x12\x16\n\x12OBJECT_FULFILLMENT\x10\x05\x12\x1b\n\x17\x43ONTEXTUAL_SEARCH_QUERY\x10\t\x12\r\n\tPDF_QUERY\x10\n\x12\x11\n\rWEBPAGE_QUERY\x10\x0bJ\x04\x08\x03\x10\x04\x42\x07H\x03\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "lens_overlay_interaction_request_metadata_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003\222\003\002\010\002"
    _globals["_LENSOVERLAYINTERACTIONREQUESTMETADATA"]._serialized_start = 118
    _globals["_LENSOVERLAYINTERACTIONREQUESTMETADATA"]._serialized_end = 1179
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA"
    ]._serialized_start = 438
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA"
    ]._serialized_end = 933
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_POINT"
    ]._serialized_start = 744
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_POINT"
    ]._serialized_end = 779
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_REGION"
    ]._serialized_start = 781
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_REGION"
    ]._serialized_end = 837
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_OBJECT"
    ]._serialized_start = 839
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_SELECTIONMETADATA_OBJECT"
    ]._serialized_end = 920
    _globals[
        "_LENSOVERLAYINTERACTIONREQUESTMETADATA_QUERYMETADATA"
    ]._serialized_start = 935
    _globals["_LENSOVERLAYINTERACTIONREQUESTMETADATA_QUERYMETADATA"]._serialized_end = (
        1004
    )
    _globals["_LENSOVERLAYINTERACTIONREQUESTMETADATA_TYPE"]._serialized_start = 1007
    _globals["_LENSOVERLAYINTERACTIONREQUESTMETADATA_TYPE"]._serialized_end = 1173
# @@protoc_insertion_point(module_scope)
