# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modality_chip_props.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'modality_chip_props.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import added_inputs_pb2 as added__inputs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19modality_chip_props.proto\x12\x04lens\x1a\x12\x61\x64\x64\x65\x64_inputs.proto\"V\n\x11ModalityChipProps\x12\x31\n\x0b\x61\x64\x64\x65\x64_input\x18\n \x01(\x0b\x32\x10.lens.AddedInputR\naddedInput\x12\x0e\n\x02id\x18\x0b \x01(\tR\x02idB\x02H\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modality_chip_props_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_MODALITYCHIPPROPS']._serialized_start=55
  _globals['_MODALITYCHIPPROPS']._serialized_end=141
# @@protoc_insertion_point(module_scope)
